name: meshgraphnets-tf115
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - tensorflow==1.15.0
    - dm-sonnet==2.0.0
    - dm-tree
    - absl-py
    - "numpy<1.20"
    - matplotlib
    - protobuf<4.0.0

